<?php

return [
  "name" => "hotel",
  "label" => "Hotels",
  "labels" => [
    "name" => "Hotels",
    "singular_name" => "Hotel",
    "add_new" => "Add New",
    "add_new_item" => "Add New Hotel",
    "edit_item" => "Edit Hotel",
    "new_item" => "New Hotel",
    "view_item" => "View Hotel",
    "search_items" => "Search Hotels",
    "not_found" => "No Hotels found",
    "not_found_in_trash" => "No Hotels found in Trash",
    "parent_item_colon" => "Parent text",
    "all_items" => "Hotels",
    "archives" => "All items",
    "insert_into_item" => "Insert into post",
    "uploaded_to_this_item" => "Uploaded to this post",
    "featured_image" => "Featured Image",
    "set_featured_image" => "Set featured image",
    "remove_featured_image" => "Remove featured image",
    "use_featured_image" => "Use as featured image",
    "filter_items_list" => "Filter posts list",
    "items_list_navigation" => "Posts list navigation",
    "items_list" => "Posts list",
    "menu_name" => "Hotels",
    "enter_title_here" => "Enter title here",
    "name_admin_bar" => "Hotel"
  ],
  "description" => "Hotel for sending internal notifications and emails to users when certain actions have been taken such as creating a story.",
  "public" => true,
  "hierarchical" => false,
  "exclude_from_search" => false,
  "publicly_queryable" => true,
  "show_ui" => true,
  "show_in_menu" => "conceptual-menu",
  "show_in_nav_menus" => false,
  "show_in_admin_bar" => true,
  "menu_position" => null,
  "menu_icon" => "dashicons-calendar-alt",
  "capability_type" => "post",
  "map_meta_cap" => true,
  "register_meta_box_cb" => null,
  "taxonomies" => [],
  "has_archive" => true,
  "rewrite" => true,
  "query_var" => "hotel",
  "can_export" => true,
  "delete_with_user" => false,
  "icon" => "email",
  "has_archive_slug" => "",
  "show_in_menu_page" => "",
  "permalink_epmask" => 1,
  "rest_base" => "hotel",
  "show_in_rest" => false,
  "supports" => [
    "title", "editor"
  ],
  "capabilities" => [
    "edit_post" => "edit_post",
    "read_post" => "read_post",
    "delete_post" => "delete_post",
    "edit_posts" => "edit_posts",
    "edit_others_posts" => "edit_others_posts",
    "publish_posts" => "publish_posts",
    "read_private_posts" => "read_private_posts",
    "read" => "read",
    "delete_posts" => "delete_posts",
    "delete_private_posts" => "delete_private_posts",
    "delete_published_posts" => "delete_published_posts",
    "delete_others_posts" => "delete_others_posts",
    "edit_private_posts" => "edit_private_posts",
    "edit_published_posts" => "edit_published_posts",
    "create_posts" => "edit_posts"
  ]
];